export const items = [
	{
		id: 1,
		name: 'coffee',
		src: '/image/coffee/coffee-1.jpg',
		title: 'Irish coffee',
		text: 'Fragrant black coffee with Jameson Irish whiskey and whipped milk',
		price: 7,
		size: [
			{ id: 1, text: 'S', count: 200, units: 'ml' },
			{ id: 2, text: 'M', count: 300, units: 'ml' },
			{ id: 3, text: 'L', count: 400, units: 'ml' },
		],
		additives: [
			{ id: 1, text: 'Sugar' },
			{ id: 2, text: 'Cinnamon' },
			{ id: 3, text: 'Syrup' },
		],
	},
	{
		id: 2,
		name: 'coffee',
		src: '/image/coffee/coffee-2.jpg',
		title: 'Kahlua coffee',
		text: 'Classic coffee with milk and Kahlua liqueur under a cap of frothed milk',
		price: 7,
		size: [
			{ id: 1, text: 'S', count: 200, units: 'ml' },
			{ id: 2, text: 'M', count: 300, units: 'ml' },
			{ id: 3, text: 'L', count: 400, units: 'ml' },
		],
		additives: [
			{ id: 1, text: 'Sugar' },
			{ id: 2, text: 'Cinnamon' },
			{ id: 3, text: 'Syrup' },
		],
	},
	{
		id: 3,
		name: 'coffee',
		src: '/image/coffee/coffee-3.jpg',
		title: 'Honey raf',
		text: 'Espresso with frothed milk, cream and aromatic honey',
		price: 5.5,
		size: [
			{ id: 1, text: 'S', count: 200, units: 'ml' },
			{ id: 2, text: 'M', count: 300, units: 'ml' },
			{ id: 3, text: 'L', count: 400, units: 'ml' },
		],
		additives: [
			{ id: 1, text: 'Sugar' },
			{ id: 2, text: 'Cinnamon' },
			{ id: 3, text: 'Syrup' },
		],
	},
	{
		id: 4,
		name: 'coffee',
		src: '/image/coffee/coffee-4.jpg',
		title: 'Ice cappuccino',
		text: 'Cappuccino with soft thick foam in summer version with ice',
		price: 5,
		size: [
			{ id: 1, text: 'S', count: 200, units: 'ml' },
			{ id: 2, text: 'M', count: 300, units: 'ml' },
			{ id: 3, text: 'L', count: 400, units: 'ml' },
		],
		additives: [
			{ id: 1, text: 'Sugar' },
			{ id: 2, text: 'Cinnamon' },
			{ id: 3, text: 'Syrup' },
		],
	},
	{
		id: 5,
		name: 'coffee',
		src: '/image/coffee/coffee-5.jpg',
		title: 'Espresso',
		text: 'Classic black coffee',
		price: 4.5,
		size: [
			{ id: 1, text: 'S', count: 200, units: 'ml' },
			{ id: 2, text: 'M', count: 300, units: 'ml' },
			{ id: 3, text: 'L', count: 400, units: 'ml' },
		],
		additives: [
			{ id: 1, text: 'Sugar' },
			{ id: 2, text: 'Cinnamon' },
			{ id: 3, text: 'Syrup' },
		],
	},
	{
		id: 6,
		name: 'coffee',
		src: '/image/coffee/coffee-6.jpg',
		title: 'Latte',
		text: 'Espresso coffee with the addition of steamed milk and dense milk foam',
		price: 5.5,
		size: [
			{ id: 1, text: 'S', count: 200, units: 'ml' },
			{ id: 2, text: 'M', count: 300, units: 'ml' },
			{ id: 3, text: 'L', count: 400, units: 'ml' },
		],
		additives: [
			{ id: 1, text: 'Sugar' },
			{ id: 2, text: 'Cinnamon' },
			{ id: 3, text: 'Syrup' },
		],
	},
	{
		id: 7,
		name: 'coffee',
		src: '/image/coffee/coffee-7.jpg',
		title: 'Latte macchiato',
		text: 'Espresso with frothed milk and chocolate',
		price: 5.5,
		size: [
			{ id: 1, text: 'S', count: 200, units: 'ml' },
			{ id: 2, text: 'M', count: 300, units: 'ml' },
			{ id: 3, text: 'L', count: 400, units: 'ml' },
		],
		additives: [
			{ id: 1, text: 'Sugar' },
			{ id: 2, text: 'Cinnamon' },
			{ id: 3, text: 'Syrup' },
		],
	},
	{
		id: 8,
		name: 'coffee',
		src: '/image/coffee/coffee-8.jpg',
		title: 'Coffee with cognac',
		text: 'Fragrant black coffee with cognac and whipped cream',
		price: 6.5,
		size: [
			{ id: 1, text: 'S', count: 200, units: 'ml' },
			{ id: 2, text: 'M', count: 300, units: 'ml' },
			{ id: 3, text: 'L', count: 400, units: 'ml' },
		],
		additives: [
			{ id: 1, text: 'Sugar' },
			{ id: 2, text: 'Cinnamon' },
			{ id: 3, text: 'Syrup' },
		],
	},
	{
		id: 9,
		name: 'tea',
		src: '/image/tea/tea-1.jpg',
		title: 'Moroccan',
		text: 'Fragrant black tea with the addition of tangerine, cinnamon, honey, lemon and mint',
		price: 4.5,
		size: [
			{ id: 1, text: 'S', count: 200, units: 'ml' },
			{ id: 2, text: 'M', count: 300, units: 'ml' },
			{ id: 3, text: 'L', count: 400, units: 'ml' },
		],
		additives: [
			{ id: 1, text: 'Sugar' },
			{ id: 2, text: 'Lemon' },
			{ id: 3, text: 'Syrup' },
		],
	},
	{
		id: 10,
		name: 'tea',
		src: '/image/tea/tea-2.jpg',
		title: 'Ginger',
		text: 'Original black tea with fresh ginger, lemon and honey',
		price: 5,
		size: [
			{ id: 1, text: 'S', count: 200, units: 'ml' },
			{ id: 2, text: 'M', count: 300, units: 'ml' },
			{ id: 3, text: 'L', count: 400, units: 'ml' },
		],
		additives: [
			{ id: 1, text: 'Sugar' },
			{ id: 2, text: 'Lemon' },
			{ id: 3, text: 'Syrup' },
		],
	},
	{
		id: 11,
		name: 'tea',
		src: '/image/tea/tea-3.jpg',
		title: 'Cranberry',
		text: 'Invigorating black tea with cranberry and honey',
		price: 5,
		size: [
			{ id: 1, text: 'S', count: 200, units: 'ml' },
			{ id: 2, text: 'M', count: 300, units: 'ml' },
			{ id: 3, text: 'L', count: 400, units: 'ml' },
		],
		additives: [
			{ id: 1, text: 'Sugar' },
			{ id: 2, text: 'Lemon' },
			{ id: 3, text: 'Syrup' },
		],
	},
	{
		id: 12,
		name: 'tea',
		src: '/image/tea/tea-4.jpg',
		title: 'Sea buckthorn',
		text: 'Toning sweet black tea with sea buckthorn, fresh thyme and cinnamon',
		price: 5.5,
		size: [
			{ id: 1, text: 'S', count: 200, units: 'ml' },
			{ id: 2, text: 'M', count: 300, units: 'ml' },
			{ id: 3, text: 'L', count: 400, units: 'ml' },
		],
		additives: [
			{ id: 1, text: 'Sugar' },
			{ id: 2, text: 'Lemon' },
			{ id: 3, text: 'Syrup' },
		],
	},
	{
		id: 13,
		name: 'dessert',
		src: '/image/dessert/dessert-1.jpg',
		title: 'Marble cheesecake',
		text: 'Philadelphia cheese with lemon zest on a light sponge cake and red currant jam',
		price: 3.5,
		size: [
			{ id: 1, text: 'S', count: 50, units: 'g' },
			{ id: 2, text: 'M', count: 100, units: 'g' },
			{ id: 3, text: 'L', count: 200, units: 'g' },
		],
		additives: [
			{ id: 1, text: 'Berries' },
			{ id: 2, text: 'Nuts' },
			{ id: 3, text: 'Jam' },
		],
	},

	{
		id: 14,
		name: 'dessert',
		src: '/image/dessert/dessert-2.jpg',
		title: 'Red velvet',
		text: 'Layer cake with cream cheese frosting',
		price: 4,
		size: [
			{ id: 1, text: 'S', count: 50, units: 'g' },
			{ id: 2, text: 'M', count: 100, units: 'g' },
			{ id: 3, text: 'L', count: 200, units: 'g' },
		],
		additives: [
			{ id: 1, text: 'Berries' },
			{ id: 2, text: 'Nuts' },
			{ id: 3, text: 'Jam' },
		],
	},
	{
		id: 15,
		name: 'dessert',
		src: '/image/dessert/dessert-3.jpg',
		title: 'Cheesecakes',
		text: 'Soft cottage cheese pancakes with sour cream and fresh berries and sprinkled with powdered sugar',
		price: 4.5,
		size: [
			{ id: 1, text: 'S', count: 50, units: 'g' },
			{ id: 2, text: 'M', count: 100, units: 'g' },
			{ id: 3, text: 'L', count: 200, units: 'g' },
		],
		additives: [
			{ id: 1, text: 'Berries' },
			{ id: 2, text: 'Nuts' },
			{ id: 3, text: 'Jam' },
		],
	},
	{
		id: 16,
		name: 'dessert',
		src: '/image/dessert/dessert-4.jpg',
		title: 'Creme brulee',
		text: 'Delicate creamy dessert in a caramel basket with wild berries',
		price: 4,
		size: [
			{ id: 1, text: 'S', count: 50, units: 'g' },
			{ id: 2, text: 'M', count: 100, units: 'g' },
			{ id: 3, text: 'L', count: 200, units: 'g' },
		],
		additives: [
			{ id: 1, text: 'Berries' },
			{ id: 2, text: 'Nuts' },
			{ id: 3, text: 'Jam' },
		],
	},
	{
		id: 17,
		name: 'dessert',
		src: '/image/dessert/dessert-5.jpg',
		title: 'Pancakes',
		text: 'Tender pancakes with strawberry jam and fresh strawberries',
		price: 4.5,
		size: [
			{ id: 1, text: 'S', count: 50, units: 'g' },
			{ id: 2, text: 'M', count: 100, units: 'g' },
			{ id: 3, text: 'L', count: 200, units: 'g' },
		],
		additives: [
			{ id: 1, text: 'Berries' },
			{ id: 2, text: 'Nuts' },
			{ id: 3, text: 'Jam' },
		],
	},
	{
		id: 18,
		name: 'dessert',
		src: '/image/dessert/dessert-6.jpg',
		title: 'Honey cake',
		text: 'Classic honey cake with delicate custard',
		price: 4.5,
		size: [
			{ id: 1, text: 'S', count: 50, units: 'g' },
			{ id: 2, text: 'M', count: 100, units: 'g' },
			{ id: 3, text: 'L', count: 200, units: 'g' },
		],
		additives: [
			{ id: 1, text: 'Berries' },
			{ id: 2, text: 'Nuts' },
			{ id: 3, text: 'Jam' },
		],
	},
	{
		id: 19,
		name: 'dessert',
		src: '/image/dessert/dessert-7.jpg',
		title: 'Chocolate cake',
		text: 'Cake with hot chocolate filling and nuts with dried apricots',
		price: 5.5,
		size: [
			{ id: 1, text: 'S', count: 50, units: 'g' },
			{ id: 2, text: 'M', count: 100, units: 'g' },
			{ id: 3, text: 'L', count: 200, units: 'g' },
		],
		additives: [
			{ id: 1, text: 'Berries' },
			{ id: 2, text: 'Nuts' },
			{ id: 3, text: 'Jam' },
		],
	},
	{
		id: 20,
		name: 'dessert',
		src: '/image/dessert/dessert-8.jpg',
		title: 'Black forest',
		text: 'A combination of thin sponge cake with cherry jam and light chocolate mousse',
		price: 6.5,
		size: [
			{ id: 1, text: 'S', count: 50, units: 'g' },
			{ id: 2, text: 'M', count: 100, units: 'g' },
			{ id: 3, text: 'L', count: 200, units: 'g' },
		],
		additives: [
			{ id: 1, text: 'Berries' },
			{ id: 2, text: 'Nuts' },
			{ id: 3, text: 'Jam' },
		],
	},
]
